USE [master]
GO

/****** Object:  Database [OficiNet]    Script Date: 09/05/2015 16:23:23 ******/
CREATE DATABASE [OficiNet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OficiNet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\OficiNet.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OficiNet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\OficiNet_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OficiNet] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OficiNet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OficiNet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OficiNet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OficiNet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OficiNet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OficiNet] SET ARITHABORT OFF 
GO

ALTER DATABASE [OficiNet] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [OficiNet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OficiNet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OficiNet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OficiNet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OficiNet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OficiNet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OficiNet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OficiNet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OficiNet] SET  ENABLE_BROKER 
GO

ALTER DATABASE [OficiNet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OficiNet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OficiNet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OficiNet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OficiNet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OficiNet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OficiNet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OficiNet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OficiNet] SET  MULTI_USER 
GO

ALTER DATABASE [OficiNet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OficiNet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OficiNet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OficiNet] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OficiNet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OficiNet] SET  READ_WRITE 
GO

